// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhTVnk6GVEmdYkFCIHbQbpqrYE4owbc0o',
    appId: '1:937527472711:web:6270dbc305cda3227c3762',
    messagingSenderId: '937527472711',
    projectId: 'v-e-commerce-29cb3',
    authDomain: 'v-e-commerce-29cb3.firebaseapp.com',
    storageBucket: 'v-e-commerce-29cb3.firebasestorage.app',
    measurementId: 'G-TWY831TW9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEOU3AUjD4KxqEoIprKM-4mimC3a1C6c0',
    appId: '1:937527472711:android:57d053a1751f9be97c3762',
    messagingSenderId: '937527472711',
    projectId: 'v-e-commerce-29cb3',
    storageBucket: 'v-e-commerce-29cb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq2rhwqN6YMVAD3bL5IRldXXfdDLbCM6I',
    appId: '1:937527472711:ios:2c3e5206a9190e137c3762',
    messagingSenderId: '937527472711',
    projectId: 'v-e-commerce-29cb3',
    storageBucket: 'v-e-commerce-29cb3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq2rhwqN6YMVAD3bL5IRldXXfdDLbCM6I',
    appId: '1:937527472711:ios:2c3e5206a9190e137c3762',
    messagingSenderId: '937527472711',
    projectId: 'v-e-commerce-29cb3',
    storageBucket: 'v-e-commerce-29cb3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
